# Generated by Django 5.1.6 on 2025-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_problems_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
